# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 797a29d67c3959231fbe434ad980ded978b4fd181480cfd22ebbc68174a6706116d0fa367ac887c387de7d3f317a1c4f339f3f00b0683ca919ca845a3d01b68d

test:
  secret_key_base: 11ba10c0645ac06baba4da62ecf49dc3000077d93491638e7885fd5837ae5cfb859a8cb83dfe9c8416afcf8531f5c4786ff82261ec26f932ab3b0d1b4deadce5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
